### ISSUE TITLE
'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by gennadiyvorgy1** [trypromptly/LLMStack#100]
It is openai-1.1.1
Hello, help please
The installation went well, it's not the first time I've done it
I create a bot, the key is added openai
I check the dialog,
but the error during dialog in bot : 'openai' has no attribute 'ChatCompletion'

This is in the terminal : 

ERROR
2023-11-16 09:54:11,626 actor Encountered <class 'AttributeError'> in
<class
'llmstack.play.actors.agent.Agent.AgentActor'>(urn:uuid:5e921f4f-e607-4e64-a148-ddd7baa962d6):
module 'openai' has no attribute 'ChatCompletion'

When testing Web bot and another

Thank you in advance

P.S. I do it in your web version and everything is fine.
I do the same on local version - error

**Comment by ajhai** [comment]
Can you try upgrading to latest release and test? `pip install --upgrade llmstack` to upgrade.

**Comment by gennadiyvorgy1** [comment]
Version It is openai - 1.1.1
Updated : pip install --upgrade llmstack
Running llmstack, everything is fine
I create a new bot - Website Chatbot
Works via VPN
Used to work with us via API 
Other applications work via API О
[Error Llmstack.txt](https://github.com/trypromptly/LLMStack/files/13386022/Error.Llmstack.txt)
penai 
Now I tried other applications - they work.
I attach the file with the bug

Thank you very much.

**Comment by ajhai** [comment]
Looks like a local environment issue. Please check your network configuration. Closing this as openai attribute issue is fixed.

**Comment by gennadiyvorgy1** [comment]
It's not on your end, I know.

but there's also a problem on the website.
https://trypromptly.com/
There is also a problem in Website Chatbot, during interaction : Connection error.
