### ISSUE TITLE
Waiting for LLMStack to be ready...

### ISSUE THREAD

**Issue by DarrellBrogdon** [trypromptly/LLMStack#12]
**Describe the bug**
Following the instructions in the README, after executing `run-llmstack.sh` I see only:

```
Waiting for LLMStack to be ready...
Waiting for LLMStack to be ready...
Waiting for LLMStack to be ready...
```

I tried going to http://localhost:3000 but it shows "502 Bad Gateway".  I've confirmed that no other processes are using port 3000.

**To Reproduce**
1. Go to '[https://github.com/trypromptly/LLMStack](https://github.com/trypromptly/LLMStack)'
2. Under 'Getting Started', run `./run-llmstack.sh`
3. Wait for it to pull containers and run them

**Expected behavior**
To be able to access the application at http://localhost:3000

**Version**
Latest

**Environment**
macOS Ventura 13.4.1 (c) (22F770820d) on a MacBook Pro, 16-inch, 2021, 32Mb, M1 processor.

**Screenshots**

**Additional context**
Add any other context about the problem here. Consider including relevant log messages from `docker compose logs`

**Comment by ajhai** [comment]
@DarrellBrogdon could you please share `docker compose logs`? It looks like server is not coming up in time likely because of some db migration issue or something.

**Comment by DarrellBrogdon** [comment]
[docker-compose-logs.txt.zip](https://github.com/trypromptly/LLMStack/files/12397934/docker-compose-logs.txt.zip)

**Comment by ajhai** [comment]
@DarrellBrogdon if you have used a password for the database in `.env` file by changing `DATABASE_PASSWORD`, can you use `POSTGRES_PASSWORD` instead and see if that works?

**Comment by DarrellBrogdon** [comment]
That worked.  Thanks @ajhai !

**Comment by ajhai** [comment]
It is a bug in the db setup logic. Fixed it and made a new release. @DarrellBrogdon for your installation, if you want to use a db password other than the default one, you will need to update the password for `llmuser` in postgres directly and then use that new password in `.env`.

Thanks for reporting this. Please let me know if you hit any other issues or have any feedback in general.
