### ISSUE TITLE
Proper Docker compose file needed for selfhosting :-))

### ISSUE THREAD

**Issue by HakaishinShwet** [trypromptly/LLMStack#133]
Dev Please provide docker compose file with necessary comments and instructions and maybe short video guide which can help in selfhosting without errors and issues. It will reduce your workload too as containerized things are bound to run perfect if build with proper packages and testings :-))
Thankyou

**Comment by ajhai** [comment]
We have decided to not ship docker files and instead ship the package via so it is easy to install. You should be able to look at `~/.llmstack/config` and create a docker file fairly easily though if you would like to install llmstack that way.
