### ISSUE TITLE
Add support for Knowledge Graph

### ISSUE THREAD

**Issue by gkorland** [trypromptly/LLMStack#18]
It seems like LLMStack is currently only support one type of stores: VectorStoreInterface.

Will you consider adding Knowledge Graph as another store type?

**Comment by ajhai** [comment]
@gkorland yes, this is something we are planning to add in the near future.

**Comment by vegito22** [comment]
We have added a sample implementation of an external database implementation https://github.com/trypromptly/LLMStack/blob/main/datasources/handlers/databases/weaviate.py. 
This should enable adding an external weaviate instance as a data source and unlock the ability to use data source search on the data. 
We will update the documentation soon with all the details.

**Comment by gkorland** [comment]
@vegito22 I don't see the file

**Comment by vegito22** [comment]
Correct URL https://github.com/trypromptly/LLMStack/blob/main/llmstack/datasources/handlers/databases/weaviate.py. Will update the docs on how to add/configure and external data source soon.

**Comment by ashunaveed** [comment]
i am getting error while downloading the package: for pip install llmstack, i am getting error message, uvloop does not support windows at the moment.
![image_2023-10-15_230428130](https://github.com/trypromptly/LLMStack/assets/43320599/67e8e403-e909-480b-917c-4d9b478fbf98)

**Comment by ajhai** [comment]
> i am getting error while downloading the package: for pip install llmstack, i am getting error message, uvloop does not support windows at the moment. ![image_2023-10-15_230428130](https://user-images.githubusercontent.com/43320599/275343603-67e8e403-e909-480b-917c-4d9b478fbf98.png)

Created a new issue #70. We will fix it soon. Thanks for reporting it.

**Comment by ajhai** [comment]
@gkorland feel free to follow https://llmstack.ai/docs/guides/add-external-datasource and add needed databases as external datasource.
