### ISSUE TITLE
Add base url to chatgpt configuration

### ISSUE THREAD

**Issue by evannorstrand-mp** [trypromptly/LLMStack#187]
For people who are using OpenAI compatible APIs for local LLMs, being able to change the baseurl and add custom model names for the ChatGpt integration opens up a lot of flexibility. 

The big issue right now is that Agent's don't allow "local llm" options.

I would love to use this tool, but it's lacking some key features right now.

**Comment by ajhai** [comment]
This is now available with openai processors. Please see provider configuration at https://docs.trypromptly.com/providers#provider-configuration. You can configure openai provider with the custom model name and base url.
