### ISSUE TITLE
Postgres is unavailable 

### ISSUE THREAD

**Issue by Joaov41** [trypromptly/LLMStack#21]
Can’t start always get Postgres no response then sleeping the unavailable.

**Comment by ajhai** [comment]
Could you please share the output of `docker compose logs`? Did you update postgres password in your `.env` file after starting it the first time by any chance?

**Comment by Joaov41** [comment]
The env file has secret, cipher, database password and open ai key. Then the path for the folders for Postgres,redis etc. didn’t see on your instructions anything about Postgres password sorry

**Comment by ajhai** [comment]
I meant database password. Can you share `docker compose logs` so we can see if there are any errors while the database is coming up?

**Comment by Joaov41** [comment]
I use orbstack not docket, just get this on the terminal: waiting for llmstack to be ready

**Comment by ajhai** [comment]
Can you get the postgres container logs? They should give some clue around what's happening when it is coming up.

**Comment by Joaov41** [comment]
Sorry don’t know exactly how to do it on orbstack?

**Comment by ajhai** [comment]
Run `docker compose logs` in the project directly and it should give you the logs (assuming you are not using linux with orbstack)

**Comment by ajhai** [comment]
Looks like you can get container logs from the orbstack menu.. see the image below.

<img width="449" alt="image" src="https://github.com/trypromptly/LLMStack/assets/431988/2b0bcdba-9358-4998-9648-1f6a72da6da4">

**Comment by Joaov41** [comment]
Thanks had not found that , very useful. 

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data/pgdata" or run initdb with an argument other than "/var/lib/postgresql/data/pgdata".
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data/pgdata" or run initdb with an argument other than "/var/lib/postgresql/data/pgdata".

**Comment by ajhai** [comment]
Check if the directory you provided for `POSTGRES_VOLUME` in `.env` file already exists and is not empty. If yes, please provide a different path or clean the existing path so LLMStack can bring up a new postgres instance.

**Comment by Joaov41** [comment]
This worked thanks so much. I will now try it none question. Is it normal that on settings the open ai token is empty? How can I be sure that I am using my api key? Thanks again for your patience. I will give feedback.

**Comment by Joaov41** [comment]
One question maximum file size is 20 mb. If I have a file, say 300 MB and split it in several of 20 MB tops, will a bot be able to go through all the files?

**Comment by ajhai** [comment]
Yes, it'll be able to do that.
