### ISSUE TITLE
[v.0.0.7] /admin "Not Found"

### ISSUE THREAD

**Issue by Moep90** [trypromptly/LLMStack#25]
**Describe the bug**
The Admin console is not accessible as described in docs.

**To Reproduce**
1. Start LLM Stack and wait until its available
2. Try access `http://<ip>:3000/admin`

**Expected behavior**
The admin console should be accessible but shows only `Not Found`

**Version**
v.0.0.7

**Environment**
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"
Docker version 24.0.5, build ced0996
Docker Compose version v2.20.3

**Screenshots**
![image](https://github.com/trypromptly/LLMStack/assets/3042152/77598c17-6f8b-476d-b9f4-42c5c898362d)

**Additional context**
```
llmstack-007-nginx-1       | 172.21.0.1 - - [05/Sep/2023:06:10:45 +0000] "GET /admin HTTP/1.1" 200 1811 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "-"
```

**Comment by ajhai** [comment]
@Moep90 can you try adding / at the end of admin url and check? Like 127.0.0.1/admin/

**Comment by Moep90** [comment]
@ajhai this works, thanks! I suggest to update the docs page accordingl
