### ISSUE TITLE
Unable to open application tag v0.2.2

### ISSUE THREAD

**Issue by nkinbox** [trypromptly/LLMStack#269]
**static/js/main.bd48de53.js file not found**
In container `app-1` the file `static/js/main.bd48de53.js` is not present.

**To Reproduce**

1. Clone repository at tag `v0.2.2`
2. run `pip install llmstack`
3. run `llmstack`
4. You will be redirected to `localhost:3000` but it will be a blank page

**Fix**
In docker-compose.yml
```
  app:
    image: ${REGISTRY:-}llmstack-app:${TAG:-v0.2.1}
```
change Tag `v0.2.1` to `v0.2.2`
```
  app:
    image: ${REGISTRY:-}llmstack-app:${TAG:-v0.2.2}
```

**Comment by ajhai** [comment]
@nkinbox thanks for catching this. I've just released a new version. Could you please try that. `pip install --upgrade llmstack`. Let me know if you see any other issues.
