### ISSUE TITLE
LLMstack api dockerfile fails to build successfully

### ISSUE THREAD

**Issue by acherla** [trypromptly/LLMStack#282]
**Describe the bug**
under docker/api/Dockerfile image fails to build due to unsuccessfully creating the client/build in the initial builder step.
  
Error:
```error building image: error building stage: failed to get files used from context: failed to get fileinfo for /kaniko/0/code/llmstack/client/build/index.html: lstat /kaniko/0/code/llmstack/client/build/index.html: no such file or directory```

Fail Step:
```
# Copy application code
COPY --from=builder /code/llmstack/client/build/index.html /code/llmstack/client/build/index.html
```

**Comment by ajhai** [comment]
How are you building it? Just run `make client` first followed by `make api`.

**Comment by acherla** [comment]
Just building it running the standard docker build command to build the image.

**Comment by ajhai** [comment]
Nope it doesn't work that way.. client files are needed in order to be able to package things fine. Please see the Makefile and read api/Dockerfile to understand how it works.

**Comment by acherla** [comment]
Yea i already did, and the dockerfile itself doesnt make any sense.  In order to make it work you have to install NPM in order to successfully built it.  This also requires knowing the python and nodejs version to initially build the container.
