### ISSUE TITLE
Multiple Dockerfile configuration issues - Results in teams unable to build llmstack

### ISSUE THREAD

**Issue by acherla** [trypromptly/LLMStack#285]
**Describe the bug**
Dockerfile for API does not properly start with CMD ["apiserver"], results in OCI $PATH not found when starting up with command: apiserver, CMD ["rqworker"] does work

Root Cause: Issue with docker-entrypoint.sh script

docker/api also has its own issues as well.

npm install
npm run build
npm start

results in no web ui application running on port 9000 in localhost, building the docker image results in a 504 gateway timeout from nginx after running the make file when accessing the application on the hosted port

Root Cause: The nginx.conf contains unnecessary upstream dependencies for proxying requests, which results in the application failing to startup if both runners and apiserver is not running.  Id recommend removing the dependency in the nginx.conf file to mitigate the UI failing to startup in the event those services are not running.  

**Overall Recommendation:**
Id highly recommend just building a common Dockerfile build instructionset for actually building this application from source as its clear its not a straightforward build process, and multiple users are running into issues just building this application from source.
1. Define the python and nodejs version required to build the app (IE python 3.11, and npm version currently undocumented)
2. in docker/app remove the nginx upstream dependencies as these can change depending on the way the user hosts the application for the 2 upstream dependencies for the apiserver and runners hostnames. 
3. in docker/api add in the npm version as a part of a build step and run the associated npm install/build commands so the llmstack/client dependencies properly build as a part of the container.  Right now the .gitignore completely ignores the local build directory in the /client folder, so I have no idea how you guys were even able to build the docker/api dockerfile with an incorrectly configured .gitignore file

**Comment by ajhai** [comment]
This is working as intended for this project. Please read more about how docker works at https://docs.docker.com/reference/dockerfile/. Feel free to fork and use a different version of Dockerfile.
