### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cometothed4rkside** [trypromptly/LLMStack#51]
llmstack-main-api-1         | ERROR 2023-09-26 20:32:15,472 consumers no close frame received or sent
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
llmstack-main-api-1         |     message = await self.read_message()
llmstack-main-api-1         |               ^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
llmstack-main-api-1         |     frame = await self.read_data_frame(max_size=self.max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
llmstack-main-api-1         |     frame = await self.read_frame(max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
llmstack-main-api-1         |     frame = await Frame.read(
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 69, in read
llmstack-main-api-1         |     data = await reader(2)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 731, in readexactly
llmstack-main-api-1         |     raise exceptions.IncompleteReadError(incomplete, n)
llmstack-main-api-1         | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
llmstack-main-api-1         |
llmstack-main-api-1         | The above exception was the direct cause of the following exception:
llmstack-main-api-1         |
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/code/llmstack/server/consumers.py", line 71, in _respond_to_event
llmstack-main-api-1         |     await self.send(text_data=json.dumps({'output': output}))
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 209, in send
llmstack-main-api-1         |     await super().send({"type": "websocket.send", "text": text_data})
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 81, in send
llmstack-main-api-1         |     await self.base_send(message)
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 226, in send
llmstack-main-api-1         |     return await self.real_send(message)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
llmstack-main-api-1         |     await self.send(data)  # type: ignore[arg-type]
llmstack-main-api-1         |     ^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
llmstack-main-api-1         |     await self.ensure_open()
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
llmstack-main-api-1         |     raise self.connection_closed_exc()
llmstack-main-api-1         | websockets.exceptions.ConnectionClosedError: no close frame received or sent
llmstack-main-api-1         | ERROR 2023-09-26 20:32:15,476 runners Task exception was never retrieved
llmstack-main-api-1         | future: <Task finished name='Task-302' coro=<AppConsumer._respond_to_event() done, defined at /code/llmstack/server/consumers.py:54> exception=ConnectionClosedError(None, None, None)>
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
llmstack-main-api-1         |     message = await self.read_message()
llmstack-main-api-1         |               ^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
llmstack-main-api-1         |     frame = await self.read_data_frame(max_size=self.max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
llmstack-main-api-1         |     frame = await self.read_frame(max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
llmstack-main-api-1         |     frame = await Frame.read(
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 69, in read
llmstack-main-api-1         |     data = await reader(2)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 731, in readexactly
llmstack-main-api-1         |     raise exceptions.IncompleteReadError(incomplete, n)
llmstack-main-api-1         | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
llmstack-main-api-1         |
llmstack-main-api-1         | The above exception was the direct cause of the following exception:
llmstack-main-api-1         |
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/code/llmstack/server/consumers.py", line 76, in _respond_to_event
llmstack-main-api-1         |     await self.send(text_data=json.dumps({'errors': [str(e)]}))
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 209, in send
llmstack-main-api-1         |     await super().send({"type": "websocket.send", "text": text_data})
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 81, in send
llmstack-main-api-1         |     await self.base_send(message)
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 226, in send
llmstack-main-api-1         |     return await self.real_send(message)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
llmstack-main-api-1         |     await self.send(data)  # type: ignore[arg-type]
llmstack-main-api-1         |     ^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
llmstack-main-api-1         |     await self.ensure_open()
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
llmstack-main-api-1         |     raise self.connection_closed_exc()
llmstack-main-api-1         | websockets.exceptions.ConnectionClosedError: no close frame received or sent
llmstack-main-api-1         | ERROR 2023-09-26 20:32:15,476 consumers no close frame received or sent
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
llmstack-main-api-1         |     message = await self.read_message()
llmstack-main-api-1         |               ^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
llmstack-main-api-1         |     frame = await self.read_data_frame(max_size=self.max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
llmstack-main-api-1         |     frame = await self.read_frame(max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
llmstack-main-api-1         |     frame = await Frame.read(
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 69, in read
llmstack-main-api-1         |     data = await reader(2)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 731, in readexactly
llmstack-main-api-1         |     raise exceptions.IncompleteReadError(incomplete, n)
llmstack-main-api-1         | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
llmstack-main-api-1         |
llmstack-main-api-1         | The above exception was the direct cause of the following exception:
llmstack-main-api-1         |
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/code/llmstack/server/consumers.py", line 71, in _respond_to_event
llmstack-main-api-1         |     await self.send(text_data=json.dumps({'output': output}))
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 209, in send
llmstack-main-api-1         |     await super().send({"type": "websocket.send", "text": text_data})
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 81, in send
llmstack-main-api-1         |     await self.base_send(message)
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 226, in send
llmstack-main-api-1         |     return await self.real_send(message)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
llmstack-main-api-1         |     await self.send(data)  # type: ignore[arg-type]
llmstack-main-api-1         |     ^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
llmstack-main-api-1         |     await self.ensure_open()
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
llmstack-main-api-1         |     raise self.connection_closed_exc()
llmstack-main-api-1         | websockets.exceptions.ConnectionClosedError: no close frame received or sent
llmstack-main-api-1         | ERROR 2023-09-26 20:32:15,477 runners Task exception was never retrieved
llmstack-main-api-1         | future: <Task finished name='Task-232' coro=<AppConsumer._respond_to_event() done, defined at /code/llmstack/server/consumers.py:54> exception=ConnectionClosedError(None, None, None)>
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 968, in transfer_data
llmstack-main-api-1         |     message = await self.read_message()
llmstack-main-api-1         |               ^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1038, in read_message
llmstack-main-api-1         |     frame = await self.read_data_frame(max_size=self.max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
llmstack-main-api-1         |     frame = await self.read_frame(max_size)
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1170, in read_frame
llmstack-main-api-1         |     frame = await Frame.read(
llmstack-main-api-1         |             ^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 69, in read
llmstack-main-api-1         |     data = await reader(2)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/asyncio/streams.py", line 731, in readexactly
llmstack-main-api-1         |     raise exceptions.IncompleteReadError(incomplete, n)
llmstack-main-api-1         | asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
llmstack-main-api-1         |
llmstack-main-api-1         | The above exception was the direct cause of the following exception:
llmstack-main-api-1         |
llmstack-main-api-1         | Traceback (most recent call last):
llmstack-main-api-1         |   File "/code/llmstack/server/consumers.py", line 76, in _respond_to_event
llmstack-main-api-1         |     await self.send(text_data=json.dumps({'errors': [str(e)]}))
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/generic/websocket.py", line 209, in send
llmstack-main-api-1         |     await super().send({"type": "websocket.send", "text": text_data})
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/consumer.py", line 81, in send
llmstack-main-api-1         |     await self.base_send(message)
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/channels/sessions.py", line 226, in send
llmstack-main-api-1         |     return await self.real_send(message)
llmstack-main-api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 327, in asgi_send
llmstack-main-api-1         |     await self.send(data)  # type: ignore[arg-type]
llmstack-main-api-1         |     ^^^^^^^^^^^^^^^^^^^^^
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
llmstack-main-api-1         |     await self.ensure_open()
llmstack-main-api-1         |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
llmstack-main-api-1         |     raise self.connection_closed_exc()
llmstack-main-api-1         | websockets.exceptions.ConnectionClosedError: no close frame received or sent
llmstack-main-api-1         | [2023-09-26 20:32:15 +0000] [154] [INFO] connection closed
llmstack-main-api-1         | sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=26, family=2, type=1, proto=6, laddr=('172.19.0.6', 43544), raddr=('104.18.6.192', 443)>
llmstack-main-api-1         | ResourceWarning: Enable tracemalloc to get the object allocation traceback
llmstack-main-api-1         | sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=39, family=2, type=1, proto=6, laddr=('172.19.0.6', 34310), raddr=('104.18.6.192', 443)>
llmstack-main-api-1         | ResourceWarning: Enable tracemalloc to get the object allocation traceback
llmstack-main-api-1         | [2023-09-26 20:32:18 +0000] [154] [INFO] ('172.19.0.8', 54618) - "WebSocket /ws/apps/0396bed1-a938-4910-8208-10dcf1690528" [accepted]
llmstack-main-api-1         | [2023-09-26 20:32:18 +0000] [154] [INFO] connection open
llmstack-main-api-1         | sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=26, family=2, type=1, proto=6, laddr=('172.19.0.6', 34312), raddr=('104.18.6.192', 443)>
llmstack-main-api-1         | ResourceWarning: Enable tracemalloc to get the object allocation traceback
llmstack-main-api-1         | sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=26, family=2, type=1, proto=6, laddr=('172.19.0.6', 54102), raddr=('104.18.6.192', 443)>
llmstack-main-api-1         | ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by ajhai** [comment]
@cometothed4rkside can you provide some reproduction steps and some details about your environment?

**Comment by ajhai** [comment]
@cometothed4rkside please reopen if you are still seeing this in latest.
