### ISSUE TITLE
Feature Request: Override the OpenAI Base URL

### ISSUE THREAD

**Issue by coreywagehoft** [trypromptly/LLMStack#6]
It would be great if we could override the OpenAI Base URL at least with an environment variable or via the UI so we could use tools like [LocalAI](https://github.com/go-skynet/LocalAI/) with this.

**Comment by sammcj** [comment]
Just came to log the same request!

**Comment by ajhai** [comment]
This is something we have in our roadmap. Will try to get this in this week.
