### ISSUE TITLE
Update documentation for processors

### ISSUE THREAD

**Issue by ajhai** [trypromptly/LLMStack#64]
Documentation is served from https://github.com/trypromptly/LLMStack/tree/main/web/docs and we use [Docusaurus](https://docusaurus.io/docs). To run documentation locally, you can use `npm start`.

As part of this task, we want to document the input, config and output schemas for all the processors. Look at the existing documentation for processors from `Promptly` at https://github.com/trypromptly/LLMStack/blob/main/web/docs/processors/promptly.md

Following the example above, we want to update documentation for all the other processors in https://github.com/trypromptly/LLMStack/tree/main/web/docs/processors.

**Comment by shubhusion** [comment]
@ajhai could you please assign this issue to me? I would like to take ownership of this task.

**Comment by ajhai** [comment]
@shubhusion thanks for working on this. Please let me know if you have any questions or need help. Feel free to ping on our discord at https://discord.gg/3JsEzSXspJ
