### ISSUE TITLE
Docker builds of rqworker seem to be broken - "/code/client/build/index.html": not found

### ISSUE THREAD

**Issue by sammcj** [trypromptly/LLMStack#7]
```
 => CACHED [stage-1  5/25] COPY --from=builder /code/base /code/base                                                                                      0.0s
 => ERROR [stage-1  6/25] COPY --from=builder /code/client/build/index.html /code/client/build/index.html                                                 0.0s
 => ERROR [stage-1  7/25] COPY --from=builder /code/client/build/static /code/client/build/static                                                         0.0s
------
 > [stage-1  6/25] COPY --from=builder /code/client/build/index.html /code/client/build/index.html:
------
------
 > [stage-1  7/25] COPY --from=builder /code/client/build/static /code/client/build/static:
------
Dockerfile:44
--------------------
  42 |     COPY --from=builder /code/apps /code/apps
  43 |     COPY --from=builder /code/base /code/base
  44 | >>> COPY --from=builder /code/client/build/index.html /code/client/build/index.html
  45 |     COPY --from=builder /code/client/build/static /code/client/build/static
  46 |     COPY --from=builder /code/common /code/common
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 33801faa-b994-4824-b268-31d19f79fcba::v47uk74k2gxiekr8yk2ky0whl: "/code/client/build/index.html": not found
ERROR: Service 'llmstack-rqworker' failed to build : Build failed
```

**Comment by ajhai** [comment]
@sammcj did you run `npm install && npm run build` in client before starting the containers with `docker compose -f docker-compose.dev.yml --env-file .env.dev up --build`?

**Comment by sammcj** [comment]
That's usually docker inside the Dockerfile though right?

So when compose renders the YAML that contains the link to the build context, it clones it (if it's a git repo), then runs docker build against it's Dockerfile, inside said Dockerfile you'd usually have all your build commands.

```yaml
  llmstack-rqworker:
    <<: [*environment, *autoupdate, *restart, *env-configs, *secopts, *gpu]
    container_name: llmstack-rqworker
    profiles:
      - "llmstack"
    image: ghcr.io/trypromptly/llmstack-api:latest
    build:
      context: https://github.com/trypromptly/LLMStack.git#main
      cache_from:
        - llmstack-rqworker:latest
    command: rqworker
    depends_on:
      - llmstack-redis
      - llmstack-postgres
    links:
      - llmstack-redis:llmstack-redis
      - llmstack-postgres:llmstack-postgres
```

**Comment by sammcj** [comment]
Oh I just saw the line in the readme:

> `Remember to run npm run build before starting your containers for development. Make sure to run npm install in the client directory before running npm start or npm run build.`

I actually skipped over it because it was greyed out 🤣 

OK interesting, so I'll need to build another intermediate container image to do the npm build 🤔

**Comment by ajhai** [comment]
> OK interesting, so I'll need to build another intermediate container image to do the npm build 🤔

Not really. `npm install && npm run build` to build the client before container build so react app is available in client/build during the [multi-stage](https://docs.docker.com/build/building/multi-stage/) build

**Comment by sammcj** [comment]
What if the client is a server / CI system / doesn't have an interactive terminal though?

NPM install requires nodejs to installed wherever it's run, so that would defeat the purpose of using containers in the first place.

**Comment by ajhai** [comment]
You wouldn't need to build anything when deploying for production. For local development, we build react client app locally and run the server python code in containers.

Will update docs to make it clear. Hope you are able to get the build working for local development after building client. If you are not looking to develop, you can simply do `docker compose up` in repo root to pull release containers from registry and bring everything up.
