### ISSUE TITLE
uvloop does not support windows at the moment

### ISSUE THREAD

**Issue by ajhai** [trypromptly/LLMStack#70]
i am getting error while downloading the package: for pip install llmstack, i am getting error message, uvloop does not support windows at the moment.
![image_2023-10-15_230428130](https://github.com/trypromptly/LLMStack/assets/43320599/67e8e403-e909-480b-917c-4d9b478fbf98)

_Originally posted by @ashunaveed in https://github.com/trypromptly/LLMStack/issues/18#issuecomment-1763455890_

**Comment by googlier325** [comment]
Same exact error message on Windows Server 2022 Datacenter

**Comment by Thegamersuni45** [comment]
Same here.

**Comment by ericsoderquist** [comment]
Hi guys, if you're experiencing this issue on a Windows system, one viable workaround is to use the Windows Subsystem for Linux (WSL) in conjunction with Ubuntu. To do this, first install Ubuntu from the Microsoft Store and set up WSL. Once that's done, open the Ubuntu terminal and run "sudo apt update" to update your package list. Following that, install Python and pip by executing "sudo apt install python3-pip". After setting up Python, you can install the necessary package using "pip install llmstack".

You may encounter an issue related to the directory path. If that's the case, you'll need to manually update your .bashrc file. Open it with "nano ~/.bashrc" and navigate to the end of the file. Add the line "export PATH=$PATH:/home/yunjae/.local/bin" to correct your PATH variable; make sure to replace /home/yunjae/.local/bin with your actual directory path. Save the file and exit. Finally, either restart your terminal or refresh the .bashrc file with "source ~/.bashrc" for the changes to take effect. This approach should help you resolve the issue you're facing.

**Comment by ajhai** [comment]
Thanks @ericsoderquist. We realized it is going to take a bit more to get llmstack work natively on Windows. Until then, WSL will be our recommended approach for windows. I will update docs to reflect this.

**Comment by ajhai** [comment]
uvloop doesn't get installed in the latest release on Windows. To use LLMStack on Windows, please use WSL2 on Windows and install LLMStack inside WSL. Check https://learn.microsoft.com/en-us/windows/wsl/install for instructions on how to install WSL on Windows.
