### ISSUE TITLE
LocalAI available models

### ISSUE THREAD

**Issue by lianee** [trypromptly/LLMStack#78]
**Describe the bug**
LLMStack always list one model, ggml-gpt4all-j, instead of allowing to choose from available models

**To Reproduce**
1. Go to Playground
2. Select LocalAI, Chat Completions
3. look models in Config Form section

**Expected behavior**
LLMStack should ask LocalAI for available models, using entrypoint /models/available

**Version**
v0.0.17

**Environment**
Ubuntu 22.04
pip install llmstack
LocalAI on another debian box with several models available (but not ggml-gpt4all-j)

**Comment by vegito22** [comment]
You should be able to type and enter the model name to override the default model name. 
<img width="969" alt="image" src="https://github.com/trypromptly/LLMStack/assets/11998761/86d43dee-3796-4719-8b61-e9106d73a750">

Let us know if that isn't working for you.

**Comment by lianee** [comment]
I can confirm you that the only model proposed is ggml-gpt4all-j
In a terminal, I can list all the models in LocalAI:

```
$ curl http://ai.example.com:8080/v1/models
{"object":"list","data":[{"id":"bert-embeddings","object":"model"},{"id":"gpt-3.5-turbo","object":"model"},{"id":"gpt4all-j","object":"model"},{"id":"lunademo","object":"model"},{"id":"stablediffusion","object":"model"},{"id":"text-embedding-ada-002","object":"model"},{"id":"whisper-1","object":"model"}]}
```

however, in LLMStack, all I have is this:
![2023-10-31_08-18](https://github.com/trypromptly/LLMStack/assets/15734521/b6bfb36b-8044-4882-b361-e04d6bb07089)
Looking at the LocalAI console, I see no request for models from LLMStack
I stopped and restarted LLMStack but still no models

The correct LocalAI address is set in settings, and if I do a test chat (How are you?" in LLMStack, the request is sent to LocalAI, and fails since it can't find the model.
![2023-10-31_10-33](https://github.com/trypromptly/LLMStack/assets/15734521/900fa1db-d7d9-4608-935b-d8f74021f7f3)

**Comment by ajhai** [comment]
@lianee LLMStack currently doesn't automatically pull the available models list from LocalAI. You will have to pick the model id from your LocalAI installation and type it in here and it will send that model id when making the request.

**Comment by lianee** [comment]
@ajhai this was just what this issue was about: "LLMStack currently doesn't automatically pull the available models list from LocalAI" when I think it should.
As it is now, it is unusable, because it doesn't pull the right/usable models.
