### ISSUE TITLE
Bind to 0.0.0.0:{port} - Spams terminal

### ISSUE THREAD

**Issue by EULArule** [trypromptly/LLMStack#85]
**Describe the bug**
When binding LLMstack to 0.0.0.0:3000 there is an issue where whenever you run the server it keeps saying, "Waiting for LLMStack server to be up...". Even when it is up, and I can access it from another machine on the same network.

System check identified no issues (0 silenced).
November 02, 2023 - 18:47:39
Django version 4.2.1, using settings 'llmstack.server.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0:3000/
Quit the server with CONTROL-C.
Waiting for LLMStack server to be up...
Waiting for LLMStack server to be up...
Waiting for LLMStack server to be up...
Waiting for LLMStack server to be up...

Expected result.
System check identified no issues (0 silenced).
November 02, 2023 - 18:47:39
Django version 4.2.1, using settings 'llmstack.server.settings'
Starting ASGI/Daphne version 4.0.0 development server at http://0:3000/
Quit the server with CONTROL-C.

**To Reproduce**
Edit the config file located at ~/.llmstack/config and change port = 3000 -> port = "0:3000"

And run:
┌─[user@fedora]─[~]
└──╼ $ llmstack

**Expected behavior**
The server starts up and does not continue outputting "Waiting for LLMStack server to be up...". This begins to fill up the screen.

**Version**
0.0.17?

**Environment**
Linux fedora 6.5.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 20 2023 x86_64 GNU/Linux
pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)

**Screenshots**
![Screenshot from 2023-11-06 08-04-17](https://github.com/trypromptly/LLMStack/assets/90616501/317968f6-b37c-4c1c-aab8-12bf71b80a6a)

![Screenshot from 2023-11-02 15-04-04](https://github.com/trypromptly/LLMStack/assets/90616501/66f4f8e4-a5c7-4a8f-b6d8-216ca5b2c22a)

**Comment by mohamed-mc** [comment]
basically you can't do it directly as you are trying, I got around it began with using ngrok

option 1:
1st- clone the repo and go into the LLMStack folder
2nd- do the pip install llmstack, run make python3 manage.py migrations app and migrate app
3rd- pip install ngrok to install, then ngrok http 3000,
 4th- go to llmstack/server/settings.py and add the generated link to both ALLOWED_HOSTS and the CSRF allowed list, make sure you do this when its running on local host, it will forward the traffic, and you can access it with the generated link

option 2:
use docker and a load balancer, you can use nginx 
option 3:
edit the project for your use case

**Comment by ajhai** [comment]
There is now `llmstack --quiet` option to limit the output to terminal as well as `llmstack --detach` to run in detached mode.
